services:
  web:
    build: .
    ports:
      - "5000:5000"
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - .:/app
    command: >
      bash -lc 'if command -v gunicorn >/dev/null 2>&1; then exec gunicorn -w 2 -b 0.0.0.0:${PORT:-5000} app:app; else echo "Gunicorn not found; starting with python app.py" && exec python app.py; fi'
