providers = ["python", "node"]

[phases.install]
# Usa el python del venv para que pip siempre exista.
cmds = [
  # Asegura venv (Nixpacks suele crearlo, pero esto lo hace idempotente)
  "python -m venv /opt/venv || true",
  "/opt/venv/bin/python -m pip install --upgrade pip setuptools wheel",
  "/opt/venv/bin/python -m pip install -r requirements.txt",

  # Instala dependencias del frontend sin depender de 'cd'
  "npm ci --prefix frontend || npm install --prefix frontend"
]

[phases.build]
cmds = [
  "npm run build --prefix frontend"
]

[start]
# Arranque del backend; Nixpacks ya añade /opt/venv/bin al PATH
cmd = "gunicorn app:app --bind 0.0.0.0:$PORT --workers 4"
