# nixpacks.toml
providers = ["python", "node"]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "cd frontend && npm ci || npm install"
]

[phases.build]
cmds = [
  "cd frontend && npm run build"
]

[start]
cmd = "gunicorn app:app --bind 0.0.0.0:$PORT --workers 4"
